scrape_configs:
  - job_name: 'node-apps'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:3000/metrics"
          - "host.docker.internal:3001/producer/metrics" 
          - "host.docker.internal:3002/consumer/metrics" 
