apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: confluentinc/cp-kafka:7.3.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            /usr/bin/kafka-topics --create --topic {{ .Values.env.kafka.topic }} --bootstrap-server {{ .Values.env.kafka.broker }} --partitions 1 --replication-factor 3;
      restartPolicy: Never
  backoffLimit: 4
