server:
  enabled: true
  service:
    type: NodePort
    nodePort: 30900  
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

rbac:
  create: true

scrape_configs:
  - job_name: 'node-apps'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "api:3000/metrics"
          - "producer:3000/producer/metrics"
          - "consumer:3000/consumer/metrics"

